version: '3.8'

services:
  oratocoach:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_DEBUG=False
      - PORT=5000
    restart: unless-stopped 